export const actionTypes = {
  UPDATE_PANTRY: "ADD_ING_TO_PANTRY",
  SET_LOGGED_IN_USER: "SET_LOGGED_IN_USER",
  LOAD_USERS: "LOAD_USERS",
  REMOVE_ING_FROM_PANTRY: "REMOVE_ING_FROM_PANTRY",
  CLEAR_PANTRY: "CLEAR_PANTRY",
  ADD_RECIPE_TO_FAV: "ADD_RECIPE_TO_FAV",
  REMOVE_RECIPE_FROM_FAV: "REMOVE_RECIPE_FROM_FAV",
  TOGGLE_IS_USER_PANTRY: "TOGGLE_IS_USER_PANTRY",
  UPDATE_FAVOURITES : "UPDATE_FAVOURITES"
};
